# Generated by Django 2.0 on 2023-05-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTGComboFinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='count_in_arena_collection',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='rules_text',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.IntegerField(db_index=True),
        ),
    ]
