# Generated by Django 2.0 on 2023-05-09 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MTGComboFinder', '0002_auto_20230509_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_a', to='MTGComboFinder.Card')),
                ('card_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_b', to='MTGComboFinder.Card')),
                ('card_c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_c', to='MTGComboFinder.Card')),
                ('card_d', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_d', to='MTGComboFinder.Card')),
            ],
        ),
    ]
