# Generated by Django 3.2.19 on 2023-05-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTGComboFinder', '0004_auto_20230509_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='combo_card_count',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
