# Generated by Django 3.2.19 on 2023-05-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTGComboFinder', '0005_combo_combo_card_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='combo_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
