# Generated by Django 3.2.19 on 2023-05-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTGComboFinder', '0008_auto_20230515_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='back_image_uri',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='front_image_uri',
            field=models.URLField(null=True),
        ),
    ]
